### ISSUE TITLE
using same setting will behave differently in different FPS

### ISSUE THREAD

**Issue by dxd39** [SPARK-inc/SPCRJointDynamicsUE4#1]
cloth is softer in low fps(~30 fps) compared with high fps(~100 fps)

**Comment by nxrighthere** [comment]
It seems like the delta time is not handled properly in simulation. 🤔

**Comment by nxrighthere** [comment]
It seems like the delta time is not handled properly in simulation. 🤔 @NoriyukiHiromoto any thoughts?

**Comment by dxd39** [comment]
I think so, the _DeltaTime alway about 0.333
![image](https://user-images.githubusercontent.com/10190265/72953790-4139fd00-3dd1-11ea-9873-8236afe30032.png)

**Comment by NoriyukiHiromoto** [comment]
Thank you for teaching me
Check it and fix it.

**Comment by nxrighthere** [comment]
@NoriyukiHiromoto You can obtain a proper delta time using [UWorld::GetDeltaSeconds](https://docs.unrealengine.com/en-US/API/Runtime/Engine/Engine/UWorld/GetDeltaSeconds/index.html).

**Comment by NoriyukiHiromoto** [comment]
We have addressed this issue with the latest version.
