### ISSUE TITLE
Update some tutorial asserts

### ISSUE THREAD

**Issue by nieyuuu** [SPARK-inc/SPCRJointDynamicsUE4#2]
It will be much more helpful if you can update the model and animation blueprint that you used in the gif

**Comment by qjh5606** [comment]
> It will be much more helpful if you can update the model and animation blueprint that you used in the gif

Do you make one model using this plugin? I found that it is hard to modify the parameters.

**Comment by nieyuuu** [comment]
> > It will be much more helpful if you can update the model and animation blueprint that you used in the gif
> 
> Do you make one model using this plugin? I found that it is hard to modify the parameters.

兄弟，这个插件我用过。跟你一样，我也很难调参数
